import { Types } from "mongoose";

// TypeScript interface for the Review schema
export interface IGlobalReview {
  _id?: Types.ObjectId; // Optional, auto-generated by Mongoose
  entityId: Types.ObjectId;
  entityType: "story" | "tool" | "influencer";
  isApproved: boolean;
  userId: Types.ObjectId;
  rating: number;
  reviewText: string;
  reviewVideoUrl?: string;
  proofUrl?: string;
  isEditorPicked: boolean;
  status: "pending" | "approved" | "rejected";
  rewardGiven: boolean;
  comments?: Types.ObjectId[];
  createdAt?: Date; // Added by timestamps option
  updatedAt?: Date; // Added by timestamps option
}